# -*- coding: utf-8 -*-
"""GGPLOT trabalho quinta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxi_KnMPcQI9WMV0cbhOPILzwLdsl8o8
"""

!pip install plotnine



import pandas as pd
from plotnine import *
from plotnine import ggplot, aes, geom_bar, theme, element_blank, labs

df = pd.read_csv('/content/drug-use-by-age.csv')

print(df.head())
print(df.columns)

df = pd.read_csv('/content/drug-use-by-age.csv')

df_scatter = pd.DataFrame({
    'x': df['age'],
    'y': df['alcohol_use']
})


grafico_disp = (
    ggplot(df_scatter, aes(x='x', y='y')) +
    geom_point(color='green') +
    labs(title='Gráfico de Dispersão', x='Eixo X', y='Eixo Y')
)

print(grafico_disp)

df = pd.read_csv('/content/drug-use-by-age.csv')

grafico_barras = (
    ggplot(df, aes(x='age', y='alcohol_use')) +
    geom_bar(stat='identity', fill='pink') +
    labs(title='Gráfico de Barras', x='age', y='alcohol_use')
)


print(grafico_barras)

import pandas as pd
from plotnine import ggplot, aes, geom_line, labs

df = pd.read_csv('/content/drug-use-by-age.csv')

df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['alcohol_use'] = pd.to_numeric(df['alcohol_use'], errors='coerce')

df = df.dropna(subset=['age', 'alcohol_use'])

df = df.sort_values(by='age')

grafico_linhas = (
    ggplot(df, aes(x='age', y='alcohol_use')) +
    geom_line(color='red') +
    labs(title='Gráfico de Linhas', x='Age', y='Alcohol Use')
)

print(grafico_linhas)

import pandas as pd
from plotnine import ggplot, aes, geom_histogram, labs

df = pd.read_csv('/content/drug-use-by-age.csv')
df['alcohol_use'] = pd.to_numeric(df['alcohol_use'], errors='coerce')
df = df.dropna(subset=['alcohol_use'])


grafico_histograma = (
    ggplot(df, aes(x='alcohol_use')) +
    geom_histogram(bins=20, fill='purple', alpha=0.7) +
    labs(title='Histograma de Uso de Álcool', x='Uso de Álcool', y='Frequência')
)


print(grafico_histograma)

import pandas as pd
from plotnine import ggplot, aes, geom_boxplot, labs

df = pd.read_csv('/content/drug-use-by-age.csv')

grafico_caixa = (
    ggplot(df, aes(x='factor(age)', y='alcohol_use')) +
    geom_boxplot(fill='yellow') +
    labs(title='Gráfico de Caixa: Uso de Álcool por Idade', x='Idade', y='Uso de Álcool')
)

print(grafico_caixa)